_wandb:
    value:
        cli_version: 0.23.1
        e:
            cw5u7xm5x7x82o92uibek6o34nr2ut2k:
                codePath: irismodelproject/notebooks/optuna_experiment.ipynb
                cpu_count: 6
                cpu_count_logical: 12
                disk:
                    /:
                        total: "1023401783296"
                        used: "778328166400"
                email: yigit.sallabas31@gmail.com
                executable: C:\Users\kysal\PycharmProjects\iris-classification-mlops\venv-sprint3\Scripts\python.exe
                git:
                    commit: ff41bebec3c2bb6230e42d87e12b6abfe1b4f46d
                    remote: https://github.com/sallabas/iris-classification-mlops.git
                host: Sallabas
                memory:
                    total: "17101778944"
                os: Windows-10-10.0.26100-SP0
                program: irismodelproject/notebooks/optuna_experiment.ipynb
                python: CPython 3.11.9
                root: C:\Users\kysal\PycharmProjects\iris-classification-mlops\irismodelproject\notebooks
                startedAt: "2026-01-05T13:17:59.288712Z"
                writerId: cw5u7xm5x7x82o92uibek6o34nr2ut2k
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 5
                - 35
                - 53
                - 105
            "2":
                - 5
                - 35
                - 53
                - 105
            "3":
                - 2
                - 13
                - 16
            "4": 3.11.9
            "5": 0.23.1
            "8":
                - 1
                - 3
            "12": 0.23.1
            "13": windows-amd64
dataset:
    value: Iris
model:
    value: RandomForestClassifier
