- name: Ansible SSH test and basic setup
  hosts: all
  become: true
  tasks:

    - name: Ping test (Ansible connectivity)
      ansible.builtin.ping:

    - name: Show hostname
      ansible.builtin.command: hostname

    - name: Ensure curl is installed
      ansible.builtin.apt:
        name: curl
        state: present
        update_cache: yes

    - name: Install required packages
      ansible.builtin.apt:
        name:
          - ca-certificates
          - gnupg
        state: present
        update_cache: yes

    - name: Install Docker
      ansible.builtin.apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Start Docker
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes

    - name: Add student user to docker group
      ansible.builtin.user:
        name: student
        groups: docker
        append: yes

    - name: Remove existing container if exists
      ansible.builtin.command:
        cmd: docker rm -f iris_container
      ignore_errors: yes

    - name: Build Docker image
      ansible.builtin.command:
        cmd: docker build -t iris-mlops .
        chdir: /home/student/iris-classification-mlops/iris-classification-mlops

    - name: Docker Run container
      ansible.builtin.command:
        cmd: docker run -d -p 8000:8000 --name iris_container iris-mlops
